# Generated by Django 4.1.1 on 2023-01-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Date_Of_Birth', models.DateField(auto_now_add=True)),
                ('Gender', models.BooleanField(choices=[('male', 'Male'), ('female', 'Female')], default=False)),
                ('Contact_Number', models.TextField(max_length=40)),
                ('Account_Type', models.BooleanField(choices=[('savings', 'Savings'), ('current', 'Current')], default=False)),
                ('Branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mypjtapp.branchmodel')),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mypjtapp.districtmodel')),
            ],
        ),
        migrations.AddField(
            model_name='branchmodel',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mypjtapp.districtmodel'),
        ),
    ]
