# Generated by Django 4.1.1 on 2023-01-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypjtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsmodel',
            name='Date_Of_Birth',
            field=models.DateField(),
        ),
    ]
